<a href="https://colab.research.google.com/github/RafaelSeri/TP_LABO_MET/blob/main/notebooks/Tp_labo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabajo Prático Grupal - Laboratorio de Métodos Cuantitativos.

In [1]:
#importamos librerías
import pandas as pd
import numpy as np

In [3]:
#Transformamos la base limpia en dataframe y creamos dos subdataframes
ruta = 'https://github.com/RafaelSeri/TP_LABO_MET/blob/main/DF/base_limpia.xlsx?raw=1'
df=pd.read_excel(ruta) #dataframe del database
df.loc[107:366, 'Período'] = (
    pd.to_datetime(df.loc[107:366, 'Período']).dt.strftime('%Y-%m')) #corregimos cómo se ven las fechas
df_base=df[['Período','Demanda Total', 'Demanda Residencial',
            'Comercio e Industria','Grandes Usuarios','Temperatura Promedio',
            'Potencia Máxima']] #dataframe para las columnas de demanda total
df_empresas=df[['Período','EDELAP SA', 'EDENOR DISTRIBUIDOR',
'EDESAL DISTRIBUIDOR', 'EDESTESA(EMP.DIST.EL.DEL ESTE)',
'EDESUR DISTRIBUIDOR', 'EMP DE ENERGIA DE RIO NEGRO SA',
'EMP DIST ENERG ATLANTICA', 'EMP. DE ENERGIA DE LA RIOJA SA',
'EMP.DIST.ENERGIA DE SALTA', 'EMP.ELECTRIC.DE MISIONES S.A.',
'EMPRESA DIS. S. ESTERO SA', 'EMPRESA JUJENIA DE ENERGIA SA',
'ENERGIA DE CATAMARCA S.A.', 'ENERGIA DE ENTRE RIOS SA',
'ENERGIA DE MENDOZA SA', 'ENERGIA SAN JUAN SA EX-EDESSA',
'EPEC DISTRIBUIDOR', 'EPEN DISTRIBUIDOR', 'EPESF DISTRIBUIDOR',
'RECURSOS Y ENERGIA FORMOSA SA', 'SECHEEP', 'SPSE SANTA CRUZ']] #dataframe para la demanda por empresa
df_empresas=df_empresas.dropna() #nos quedamos con las filas con datos no nulos

In [4]:
df_base.head(10)

,Período,Demanda Total,Demanda Residencial,Comercio e Industria,Grandes Usuarios,Temperatura Promedio,Potencia Máxima
0,2005,92332.950000,30086.495000,43102.875000,19143.580,18.363667,16143.0
1,2006,96812.800000,32608.358000,41291.755000,22912.687,18.575000,17395.0
2,2007,102950.300000,37111.179000,43484.381000,22354.740,17.650000,18345.0
3,2008,105958.100000,38610.044000,43060.486000,24287.570,19.050000,19126.0
4,2009,104622.400000,39564.998000,42648.252000,22409.150,18.583333,19566.0
5,2010,110798.400000,42652.349000,44877.591000,23268.460,18.066667,20843.0
6,2011,116487.900000,44864.373000,46414.037000,25209.490,18.316667,21564.0
7,2012,121225.000000,47758.776142,47609.042858,25857.181,18.691667,21949.0
8,2013,125234.334819,50389.163548,48523.871271,26321.300,18.508333,23794.0
9,2014,126467.080005,51444.141258,49041.038747,25981.900,18.625000,24034.0

In [5]:
df_empresas.head(10)

,Período,EDELAP SA,EDENOR DISTRIBUIDOR,EDESAL DISTRIBUIDOR,EDESTESA(EMP.DIST.EL.DEL ESTE),EDESUR DISTRIBUIDOR,EMP DE ENERGIA DE RIO NEGRO SA,EMP DIST ENERG ATLANTICA,EMP. DE ENERGIA DE LA RIOJA SA,EMP.DIST.ENERGIA DE SALTA,...,ENERGIA DE CATAMARCA S.A.,ENERGIA DE ENTRE RIOS SA,ENERGIA DE MENDOZA SA,ENERGIA SAN JUAN SA EX-EDESSA,EPEC DISTRIBUIDOR,EPEN DISTRIBUIDOR,EPESF DISTRIBUIDOR,RECURSOS Y ENERGIA FORMOSA SA,SECHEEP,SPSE SANTA CRUZ
9,2014,2378.511734,20695.281360,1193.612775,746.308529,17088.832858,1263.940622,2626.465450,1115.073941,1756.432529,...,917.436808,2582.879226,3381.433381,1586.920665,8626.852806,871.880839,9288.999704,1179.717698,2435.771533,509.829498
10,2015,2545.617350,22207.382744,1236.492585,757.037308,18064.754754,1364.005442,2773.577417,1164.582836,1857.603610,...,950.285160,2763.273181,3462.140383,1719.146438,8933.013610,946.857694,9720.505696,1227.170328,2592.745982,561.240525
11,2016,2816.603973,24457.502373,1463.685001,748.361903,19477.180554,1420.263874,2807.465483,1249.020304,2015.020280,...,1054.115441,2925.621791,3403.144289,1942.065602,9298.827150,955.509350,10190.968190,1306.644835,2728.039692,576.744343
12,2017,2599.359071,22013.499165,1309.465478,786.936648,17565.433992,1312.805676,2705.760206,1312.898964,1923.532251,...,1002.080749,2821.614678,3361.309857,1873.970624,9121.949346,916.490891,9775.564765,1302.460587,2786.641335,598.480563
13,2018,2669.383878,22229.026813,1270.556777,766.126704,17641.587070,1338.813501,2725.457446,1298.939775,1981.455074,...,1005.302807,2863.528905,3219.126411,1838.278127,9270.803419,905.697463,9860.999109,1353.646156,3005.021072,634.323649
14,2019,2645.891115,21457.996457,1191.097932,750.434310,17259.700152,1333.858410,2701.365270,1271.999833,1954.465326,...,956.130952,2694.750524,3218.463510,1858.325354,9051.223623,925.597001,9534.419612,1313.950611,2799.754658,607.629404
15,2020,2711.558147,21832.353822,1195.408044,775.716584,17204.586472,1345.445637,2704.004985,1342.124114,1987.893337,...,1008.386596,2763.435305,3258.854700,1919.961333,8937.594030,871.728201,9565.973522,1365.666278,2908.167260,591.680364
16,2021,2776.489291,22745.737335,1237.140935,759.995944,17840.844230,1389.538127,2851.009324,1350.176952,2017.121080,...,1030.774775,2910.647804,3278.585714,1916.754280,9305.317449,925.596571,10065.769775,1323.755166,2941.126474,603.347696
17,2022,2913.781006,23458.021572,1350.081058,817.037104,18427.023689,1428.012000,3078.575101,1424.227527,2121.586051,...,1119.631980,3004.899320,3522.982558,2065.957962,9973.664466,990.327704,10477.002686,1364.145493,3025.244558,629.857137
18,2023,2945.583410,23834.970922,1323.607798,815.382020,18912.211129,1443.877441,3142.837444,1453.243378,2184.997755,...,1169.607750,3075.897016,3557.126656,2095.567441,10069.796388,1017.380920,10469.861495,1486.090682,3236.295624,632.622932